### ISSUE TITLE
Feature request: Ability to swap out the backend for something on-prem

### ISSUE THREAD

**Issue by Whoaa512** [FrigadeHQ/remote-storage#14]
Would be lovely to configure the remote host to be something other than the public API

Ideally with a spec that the backend must conform to.

Thanks!

**Comment by christianmat** [comment]
Hey there! The Remote host can be set to anything using the `serverAddress` param in the config as such:

```
const remoteStorage = new RemoteStorage({
  serverAddress: 'https://api.remote.storage'
})
```

Furthermore, the spec for the backend is available through OpenAPI/Swagger here: https://github.com/FrigadeHQ/remote-storage/blob/main/apps/remote-storage-server/swagger-spec.json

We'll soon publish a website that has a more user-friendly spec on the API.
