### ISSUE TITLE
SECURITY: Certificate with private key in repository

### ISSUE THREAD

**Issue by htho** [FrigadeHQ/remote-storage#17]
Hi,

I am not a security expert, but storing private keys in (public) repositories is a huge red flag.
Someone might use the certificate to pretend to be the owner of the cert.

If it is a false positive, add a README.
Otherwise you need to invalidate the cert, issue a new one and rewrite the repositories history.

**Comment by christianmat** [comment]
Hey there! These are self-signed certs used for development only to run https/ssl locally. I just updated the docs with this.
