### ISSUE TITLE
Security Threat found

### ISSUE THREAD

**Issue by abhishekpatel946** [FrigadeHQ/remote-storage#19]
Hi team,  while exploring the codebase found the hardcoded keys, cert etc.. it's a potential risk for the project like opensource. I will paste all the code block here for your references.

https://github.com/FrigadeHQ/remote-storage/blob/bfb4fa144f7198cfba1acb9d0723eafc5a76345a/apps/www/pages/_app.tsx#L14
https://github.com/FrigadeHQ/remote-storage/blob/bfb4fa144f7198cfba1acb9d0723eafc5a76345a/apps/remote-storage-server/certs/server.crt#L1
https://github.com/FrigadeHQ/remote-storage/blob/bfb4fa144f7198cfba1acb9d0723eafc5a76345a/apps/remote-storage-server/certs/server.csr#L1
https://github.com/FrigadeHQ/remote-storage/blob/bfb4fa144f7198cfba1acb9d0723eafc5a76345a/apps/remote-storage-server/certs/server.key#L1

If possible so port this hardcoding into env or somewhere else just like you did for redis configuration.

**Comment by christianmat** [comment]
Hey there! These keys are all public information. The posthog key used for the demo website is publicly available as well on https://remote.storage
