### ISSUE TITLE
Another remotestorage

### ISSUE THREAD

**Issue by rosano** [FrigadeHQ/remote-storage#22]
This looks great, congrats on your release 👍🏽. Good that your server is also designed to be self-hosted. Have you considered making it available for ['one-click' deploys](https://easyindie.app)?

I can't help but think of the remoteStorage project that's been around [since at least 2010](https://github.com/remotestorage/remotestorage.js/graphs/contributors) I guess it's a reflection of how programmers tend to name things… Anyway maybe there's a way to connect the two projects when there are shared goals. The community project seeks to become an [internet standard](https://datatracker.ietf.org/doc/html/draft-dejong-remotestorage-22). Will also post this elsewhere as I'm not sure which channel is best.

**Comment by christianmat** [comment]
One click deploys is coming soon!

On your other note, I think the two projects are substantially different. While this project simply seeks to create a secure backend for localStorage, the project you linked has a ton of features that have nothing to do with the goal of this project (e.g. linking your Dropbox or Google Drive account). They have very little in common except for the name.

**Comment by raucao** [comment]
remoteStorage is the name of the protocol. The reference client library called remoteStorage.js (note the **.js**) also has support for other back-ends, but that has nothing to do with the remoteStorage protocol.

Here is the IETF tracker for the spec: https://datatracker.ietf.org/doc/draft-dejong-remotestorage/

The two projects do have quite a bit in common actually. The idea of the remoteStorage protocol is also to sync your localStorage across devices, but it has auth and folder permissions for apps baked in via OAuth, and it is more focused on letting users choose which server syncs their data (can be custodial or self-hosted).

Considering that the remoteStorage name and spec has been around for over a decade now, and that people are already confused about this one being connected to the original one in some way, I think it would be reasonable to consider a name change to eliminate more misunderstandings in the future, and to make it easier to find this project on search engines in the first place.

**Comment by christianmat** [comment]
Appreciate the feedback. Closing this for now, but will keep this in the mind as both projects evolve in the future.

**Comment by DustinWehr** [comment]
I wasted a lot of time because of this.
I love how easy to use your API is, but for the love of god, change the name.
