### ISSUE TITLE
Conflict Resolution Strategy

### ISSUE THREAD

**Issue by abakermi** [FrigadeHQ/remote-storage#23]
The `RedisService` currently lacks a mechanism to handle conflicts that arise when concurrent operations attempt to update the same key with different values. We can resolve that based on timestamp ,the approach involves modifying the set method to include a timestamp and compare it with the timestamp of the current data in Redis. If a conflict is detected (the existing data is newer), the update will be rejected. This enhancement is crucial for maintaining data integrity in scenarios with concurrent data operations.

**Comment by christianmat** [comment]
Hey @abakermi, this is a good point. Feel free to open a PR that addresses this. Make sure to also include any proposed fixes in the sqlite data connector.
