### ISSUE TITLE
Array-based value stored as a string

### ISSUE THREAD

**Issue by calebmpeterson** [FrigadeHQ/remote-storage#25]
Can [this condition](https://github.com/FrigadeHQ/remote-storage/blob/main/packages/js-client/src/core/remote-storage.ts#L48) be expanded to consider strings starting with `'['` as well so that `setItem('my-key', [0, 1, 2])` can be read with subsequent `getItem('my-key')` calls as an `Array` instead of a `string`?

**Comment by calebmpeterson** [comment]
I'm happy to submit a PR if this is an acceptable change.

**Comment by christianmat** [comment]
@calebmpeterson thanks for calling this out, yes that's definitely a bug. Feel free to open a PR to fix this.

**Comment by calebmpeterson** [comment]
PR opened: https://github.com/FrigadeHQ/remote-storage/pull/26

**Comment by christianmat** [comment]
Appreciate the fix. This is now released in `remote-storage@1.0.5`
